### ISSUE TITLE
Let user chose which way to synch the first time?

### ISSUE THREAD

**Issue by ghost** [ArtSabintsev/Zephyr#15]
I started to implement iCloud sync into an _existing_ app when I came across your library. As it would be implemented to add iCloud synch as a new feature, there is the scenario where a user has two (or more) devices with local settings each. The current logic would sync the local settings from the first device that starts the app to iCloud and then overwrite the second device's local settings without checking in if this is desired. For this case an option would be great that asks the user once which settings to use. Any thoughts on this? Thanks and thank you for this great piece of code.

**Comment by ArtSabintsev** [comment]
This is the expected behavior. The implicit idea behind the library is that you'd want to have 100% synchronization across all devices. It checks whatever the latest data is, and synchronizes it that way.

If you don't want to have pure synchronization across devices, it might be wise for you to implement a check yourself, and only execute Zephyr's sync function after the user states that they want to override local settings on a specific device.

Closing this issue, but feel free to comment as I will continue responding.

**Comment by ghost** [comment]
I see your point and it works great when you ship version 1.0 of your app with the library. 

But if you include it at a later stage, you encounter a situation where you have two or more sets of valid settings and Zaphyr just cannot know which set it should use for it's pure synchronization across devices. It's a one time questions before the library continues to do what it does. 

I will explore how to implement this and see if it can be put into a pull request ;)

**Comment by ArtSabintsev** [comment]
@ghowen 

As I said earlier, if you have two sets of data, and you don't want to automatically sync that data, just fetch the data on the server (using your own custom code around the `NSUbuqituitousKeyValueStore` API) before performing sync, and ask the user which data they want to keep. If they want to override it, then do synchronization

Please do not spend the time making a pull request for this feature, as it goes beyond the scope of this library. I like keeping my libraries simple, and this library does exactly what I want it to do ay this point in time.

Best of luck!
