### ISSUE TITLE
A couple of qustions

### ISSUE THREAD

**Issue by srstanic** [ArtSabintsev/Zephyr#20]
Hi, first I wanted to thank you for writing this library. It really makes the usage of `NSUbiquitousKeyValueStore` effortless.

Now, I was looking into the Zephyr code and I have a couple of questions that aren't necessarily issues, but they might be. 

In the `syncToCloud(key:value:)` local storage observer is unregistered before the value is stored to the ubiquitous storage and synchronized. Is it possible that at that same time another thread updates the value in the local storage with the same key and that update doesn't get synced with the ubiquitous storage because the observer is unregistered at that point? Why is local storage observer unregistered during syncing to the iCloud anyway?

Also, it seems like [different reasons](https://developer.apple.com/reference/foundation/foundation_enumerations/1433687-change_reason_values) for the occurrence of `NSUbiquitousKeyValueStoreDidChangeExternallyNotification`  aren't handled by Zephyr. Do you plan to add that anytime soon?

Thanks in advance for your response!

**Comment by ArtSabintsev** [comment]
Hey - thanks for the message.

I unregister and reregister a key to avoid an infinite loop from cropping up during synchronization. 

I have no plans on handling `NSUbiquitousKeyValueStoreDidChangeExternallyNotification`, because I don't see a need to do so. The idea with Zephyr is to obtain whatever the latest value on the cloud is, and to overwrite it `UserDefaults`, no matter the reason.

There's a check `(remoteStoredDate.timeIntervalSince1970 > localStoredDate.timeIntervalSince1970)` in the `keysDidChangeOnCloud` that makes sure nothing syncs to the device unless the cloud value has a newer timestamp than what's currently stored.

Hope this clears up your questions.

**Comment by ArtSabintsev** [comment]
No response, so I'm closing this issue for now.
