### ISSUE TITLE
Can not compile in Xcode 11 beta 5 and Swift 5

### ISSUE THREAD

**Issue by funkenstrahlen** [ArtSabintsev/Zephyr#41]
The compiler complains that this notification key got renamed:

https://github.com/ArtSabintsev/Zephyr/blob/ced975fb973d5dbd045c8e2d23e3b5f13239b245/Sources/Zephyr.swift#L73

Using Zephyr 3.4.1

**Comment by ArtSabintsev** [comment]
I currently don’t have a branch up for the latest beta. I’ll look into doing it shortly

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtSabintsev** [comment]
I'm not seeing this error in Xcode11b5. Downloading b6 right now. 

Can you send me a sample project that is throwing an error?

**Comment by funkenstrahlen** [comment]
Sorry for not providing more details in the first report of the issue.

When using Zephyr via Cocoapods on Xcode Beta 6 I can compile without any errors now.

The compilation error is still present when using Xephyr via Swift Package Manager. I attached a sample project that shows the error:

[ZephyrCompileIssue.zip](https://github.com/ArtSabintsev/Zephyr/files/3519319/ZephyrCompileIssue.zip)

**Comment by ArtSabintsev** [comment]
This seems to be a bug in Xcode 11. I've confirmed it by trying to put the existing notification I'm using, and the one that the compiler recommends, and another one, since the compiler recommends the wrong fix.

Thanks for bringing it up to my attention, but this is a bug.

It might actually be worth posting to https://feedbackassistant.apple.com/

**Comment by funkenstrahlen** [comment]
I understand. Thank you for looking into it! 😊

**Comment by ArtSabintsev** [comment]
Thanks for bringing it up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
